### ISSUE TITLE
Whole word find-replace

### ISSUE THREAD

**Issue by miguelnx** [pgilfernandez/multiple-find-replace#2]
Hola Pablo.
Muchas gracias por tu código, nos salva la vida a muchos.
¿Es posible realizar un «Buscar-reemplazar» a una palabra completa-concreta en lugar de cadena de texto, es decir, como la búsqueda de Atom «Whole word»?.

Ejemplo:
TRANSMISIÓN => TRANSMISSION
SI => YES
La primera línea la cambiaría de manera correcta, pero al leer la segunda línea encontraría la cadena «SI» dentro de «TRANSMISSION» y reemplazaría dejando «TRANSMISYESON»

Muchas gracias.

**Comment by pgilfernandez** [comment]
uhh, no sé como pero se me ha pasado esta sugerencia totalmente... perdona.
Sí, me parece una muy buena mejora, déjame que lo mire y lo incluyo.

Un saludo

**Comment by pgilfernandez** [comment]
Closed via c14100e
