### ISSUE TITLE
Newline attached to replacements

### ISSUE THREAD

**Issue by unseenscholar** [pgilfernandez/multiple-find-replace#3]
Hi, I'm having a little trouble. The replaced words all end up being attached with a newline character at the end. Looks normal after being replaced in the atom editor but copy pasting it shows a new line character at the end.

![image](https://user-images.githubusercontent.com/92890439/138167054-b0808dbd-138b-4fc5-89c3-df039a43d7ea.png)

After copy pasting it looks like this
![image](https://user-images.githubusercontent.com/92890439/138167166-305d5c25-24ab-42d1-97a7-37d774d6eae0.png)

The newline thing seems to be added during replacement because replacing half a word and searching for the complete word after replacement can't identify it.

**Comment by Daniel-Dan-Espinoza** [comment]
I compared some of the older text files I had replaced without issue and noticed that the Line Ending used in those files were 'LF', while the one used in the current file is 'CRLF'. I do not know if it is of any significance, but changing the Line Ending of the template file to 'LF' seems to have fixed the issue for me.
