### ISSUE TITLE
"sintax" is a misspelling of "syntax"

### ISSUE THREAD

**Issue by RichardJJG** [pgilfernandez/multiple-find-replace#4]
Thanks so much for your work on this package; it's a very good idea.

One minor error is that, as best I can tell, you misspelled "syntax" throughout as "sintax".

**Comment by pgilfernandez** [comment]
Thanks!

Closed via [1598b1c](https://github.com/pgilfernandez/multiple-find-replace/commit/1598b1c396f87ebea85e5720d9586fff25473d9c)
