### ISSUE TITLE
"The template could not been created" has incorrect grammar

### ISSUE THREAD

**Issue by RichardJJG** [pgilfernandez/multiple-find-replace#5]
I think the intended meaning is "it was not possible to create the template". 

If so, the grammatically correct version of your sentence is "The template could not be created".

**Comment by pgilfernandez** [comment]
Thanks again
=)

Closed via [13c361e](https://github.com/pgilfernandez/multiple-find-replace/commit/13c361e27dbb9d5cacc193aa5a7d6efa450397a1)
